language: php

php:
  - 7.0
  - 7.1
  - hhvm
  - nightly

env:
  matrix:
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

before_script:
  - if [ "$DEPENDENCIES" = "high" ]; then composer --prefer-source update; fi;
  - if [ "$DEPENDENCIES" = "low" ]; then composer --prefer-lowest --prefer-source update; fi;

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml --exclude-group Functional
  - ./vendor/bin/phpunit --group=Functional
  - php -n ./vendor/bin/phpbench run --report=aggregate --revs=500 --iterations=50 --warmup=3
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/ ./benchmarks

after_script:
  - if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
