language: php

php:
  - 7
  - hhvm

before_script:
  - composer self-update
  - composer update --prefer-source --dev

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml --exclude-group Functional
  - ./vendor/bin/phpunit --group=Functional
  - php -n ./vendor/bin/athletic -p ./tests/GeneratedHydratorPerformance/ -f GroupedFormatter
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/

after_script:
  - if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi